name: Check issue title with action

on:
  issues:
    types: [opened]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  check-issue-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check issue title
        uses: ./.github/actions/check-issue-title-action
        with:
          issue-title: ${{ github.event.issue.title }}